### ISSUE TITLE
Mapping data field of DateTimeOffset

### ISSUE THREAD

**Issue by StevenKlein6661** [AutoMapper/AutoMapper.Data#50]
When I have a field that is a DateTimeOffset, I get the error:
`Value cannot be null.
Parameter name: con
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, ConstructorInfo con)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers, IMemberConfiguration parent)
   at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers)
   at AutoMapper.ProfileMap.<>c__DisplayClass70_0.<MapDestinationPropertyToSource>b__0(IMemberConfiguration _)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.ProfileMap.MapDestinationPropertyToSource(TypeDetails sourceTypeInfo, Type destType, Type destMemberType, String destMemberInfo, LinkedList`1 members)
   at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)
   at AutoMapper.ProfileMap.BuildTypeMap(IConfigurationProvider configurationProvider, ITypeMapConfiguration config)
   at AutoMapper.ProfileMap.Register(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at CombinedPublic.Service.Repository.InmateRepository..ctor(ISqlClient sqlClient) in C:\\Users\\sklein\\source\\repos\\view-services\\CombinedPublic.Service\\Repository\\InmateRepository.cs:line 47"
`

I assume that in DataRecordMemberConfiguration.cs, DateTimeOffset needs to be added to _treatAsPrimitives.  Is there any way to do this?

**Comment by hardikshah7** [comment]
Hi @lbargaoanu  - I'm having the same issue with mapping TimeSpan field. When do you plan to publish a new version that includes this fix?

**Comment by lbargaoanu** [comment]
cc @jbogard

**Comment by lbargaoanu** [comment]
Meanwhile you can use the MyGet build. https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Data

**Comment by hardikshah7** [comment]
Thank you!
