### ISSUE TITLE
AddDataReaderMapping not ignoring recursive class property

### ISSUE THREAD

**Issue by RokasBagdonas** [AutoMapper/AutoMapper.Data#63]
Hi,

I'm getting an error when setting up `MapperConfiguration` with AddDataReaderMapping() for a class that has self reference:

Configuration:
```
var config = new MapperConfiguration(cfg =>
 {
                cfg.AddDataReaderMapping();
                cfg.CreateMap<IDataReader, SimpleNode>()
                   .ForMember(sn => sn.Parent, opt => { opt.Ignore();});
 });
```

The class:
```
    public class SimpleNode
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public SimpleNode Parent { get; set; }
        public IEnumerable<SimpleNode> Children { get; set; }
    }
```

The error:
> System.InvalidOperationException
  HResult=0x80131509
  Message=Opcodes using a short-form index cannot address a local position over 255.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, LocalBuilder local)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.EmitPropertyMapping(ILGenerator il, Type destType, Type destMemberType, String nameToSearch)
   at AutoMapper.Data.Configuration.Conventions.DataRecordMemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, List`1 resolvers, IMemberConfiguration parent, Boolean isReverseMap)
   at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, List`1 resolvers, Boolean isReverseMap)
   at AutoMapper.ProfileMap.MapDestinationPropertyToSource(TypeDetails sourceTypeDetails, Type destType, Type destMemberType, String destMemberName, List`1 members, Boolean reverseNamingConventions)
   at AutoMapper.TypeMap..ctor(Type sourceType, Type destinationType, ProfileMap profile, Boolean isReverseMap)
   at AutoMapper.ProfileMap.BuildTypeMap(IGlobalConfiguration configurationProvider, ITypeMapConfiguration config)
   at AutoMapper.ProfileMap.Register(IGlobalConfiguration configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)

Note that I do not need to map the `Parent` (this is done manually). I just want to ignore that field. 
Automapper version: 11.0.1
Automapper.Data version: 6.0.0

Thank you for any help!
Rokas

**Comment by jbogard** [comment]
I don't work with this library, but I'll be happy to take a PR that fixes this.
