### ISSUE TITLE
Error when running in Azure Function, Method not found: AddMemberConfiguration()

### ISSUE THREAD

**Issue by grok314** [AutoMapper/AutoMapper.Data#65]
Hi, 
I ran the following code in LINQPad 7 with .NET 3.1 selected and it works. 
But when I run it from an Azure Function locally on my dev machine, it doesn't. 
Seems like an issue.

Any help would be appreciated. 

**The error:**
```
[2022-11-02T17:37:20.058Z] PoChangeNotif trigger function, executed at: 11/2/2022 1:37:20 PM
[2022-11-02T17:37:20.086Z] System.MissingMethodException: Method not found: 'AutoMapper.Configuration.Conventions.IMemberConfiguration AutoMapper.Internal.IProfileExpressionInternal.AddMemberConfiguration()'.
[2022-11-02T17:37:20.090Z]    at AutoMapper.Data.ConfigurationExtensions.AddDataRecordMember(IProfileExpression profile)[2022-11-02T17:37:20.092Z]    at AutoMapper.Data.ConfigurationExtensions.AddDataReaderMapping(IMapperConfigurationExpression configuration, Boolean enableYieldReturn)
[2022-11-02T17:37:20.093Z]    at AutoMapper.Data.ConfigurationExtensions.AddDataReaderMapping(IMapperConfigurationExpression configuration)
[2022-11-02T17:37:20.095Z]    at Project.AzureAlerts.VendorPoChangeNotifFunction.<>c.<Run>b__1_0(IMapperConfigurationExpression cfg) in D:\Dev\VS2019\Project.AzureAlerts\Project.AzureAlerts\VendorPoChangeNotifFunction.cs:line 33
[2022-11-02T17:37:20.096Z]    at AutoMapper.MapperConfiguration.Build(Action`1 configure)
[2022-11-02T17:37:20.097Z]    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
[2022-11-02T17:37:20.098Z]    at Project.AzureAlerts.VendorPoChangeNotifFunction.Run(TimerInfo myTimer, ILogger log) in D:\Dev\VS2019\Project.AzureAlerts\Project.AzureAlerts\VendorPoChangeNotifFunction.cs:line 31
```

**References:**
```
    <PackageReference Include="AutoMapper.Data" Version="6.0.0" />
    <PackageReference Include="DevExpress.Xpo" Version="22.1.6" />
    <PackageReference Include="DotLiquid" Version="2.2.656" />
    <PackageReference Include="MailKit" Version="3.4.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.1.2" />
```

**The code:**
```csharp
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using AutoMapper;
using AutoMapper.Data;
using Project.AzureAlerts.Models;
using DevExpress.Xpo;
using DevExpress.Xpo.DB;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

namespace Project.AzureAlerts
{
    public static class VendorPoChangeNotifFunction
    {
        [FunctionName("PoChangeNotif")]
        public static void Run([TimerTrigger("*/10 * * * * *")]TimerInfo myTimer, ILogger log)
        {
            log.LogInformation($"PoChangeNotif trigger function, executed at: {DateTime.Now}");

            IMapper map;
            try
            {
                var config = new AutoMapper.MapperConfiguration(cfg =>
                {
                    cfg.AddDataReaderMapping();
                    cfg.CreateMap<IDataReader, ChangePoRecord>();
                });

                map = config.CreateMapper();
            }
            catch (Exception ex)
            {
                log.LogInformation(ex.ToString());

                throw ex;
            }

            InitializeDatabase();

            var sql = 
@"select upo.*, ven.email
from [dbo].[vwPurchOrders] upo
inner join dbo.Vendors ven ON upo.VendorID = ven.pk
where ven.portal= 1";

            var selectedData = XpoDefault.Session.ExecuteQueryWithMetadata(sql);

            var reportTable = BuildTableFromXpoResult(selectedData);

            var list = new List<ChangePoRecord>();
            var reader = reportTable.CreateDataReader();
            while(reader.Read())
            {
                list.Add(map.Map<ChangePoRecord>(reader));
            }

            log.LogInformation($"fifth PONo: {list[4].PONo}");
        }
    // ... more stuff
    }
}
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
