### ISSUE TITLE
Automapper running under IIS 8.0 (Win 2012 R2) - Common Language Runtime detected an invalid program

### ISSUE THREAD

**Issue by jumas45** [AutoMapper/AutoMapper.Data#9]
Hi, 

I am currently using Automapper 4 via NuGet and it seems to be working fine on all developer machines which use IIS Express. As soon as I deploy to the server (Win 2012 R2), I get the dreaded "Common Language Runtime detected an invalid program exception". 

Interestingly the problem doesn't when I am using dynamic map, only when I try to create an explicit map as shown by creating a custom profile.

---------------------------
protected override void Configure()
        {
            Mapper.CreateMap<IDataReader, SalesInfo>()
                .ForMember(dest => dest.IsWipType,
                    option =>
                        option.MapFrom(
                            row =>
                                (YesNo)
                                    Enum.Parse(typeof(YesNo),
                                        row["IsWipType"].ToString(), true)));
        }

------------------------------------

I have tried the solution provided under https://github.com/AutoMapper/AutoMapper/issues/242 but no luck as the patch is not applicable to my server. 

The solution provided under https://github.com/AutoMapper/AutoMapper/issues/664 doesnt seem to apply to me as even if I remove the explicit mappings, it give the same error.

NOTE: This problem does not happen when run as a console application on the same server. Only when run inside regular IIS.

The error that I get is as follows:

-------------------------------
AutoMapper.AutoMapperMappingException was unhandled by user code
  HResult=-2146233088
  Message=

Mapping types:
IDataReader -> IList`1
System.Data.IDataReader -> System.Collections.Generic.IList`1[[Domain.CategoryInfo, Domain, Version=0.9.5582.23112, Culture=neutral, PublicKeyToken=null]]

Destination path:
IList`1

Source value:
System.Data.DataTableReader
  Source=AutoMapper
  StackTrace:
       at DomainServices1.CategoryInfoServiceAccess.GetAllCategoryInformation(Int32 companyId) in c:\Users\\Documents\Visual Studio 2013\Projects\MvcApplication1\MvcApplication1\CategoryInfoServiceAccess.cs:line 31
       at MvcApplication1.Controllers.ValuesController.<Get>d__2.MoveNext() in c:\Users\\Documents\Visual Studio 2013\Projects\MvcApplication1\MvcApplication1\Controllers\ValuesController.cs:line 40
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(Object list)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value)
       at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value)
       at System.Net.Http.Formatting.JsonMediaTypeFormatter.<>c__DisplayClassd.<WriteToStreamAsync>b__c()
       at System.Threading.Tasks.TaskHelpers.RunSynchronously(Action action, CancellationToken token)
  InnerException: System.InvalidProgramException
       HResult=-2146233030
       Message=Common Language Runtime detected an invalid program.
       Source=Domain
       StackTrace:
            at DynamicCreate(IDataRecord )
            at AutoMapper.Mappers.DataReaderMapper.LoadDataReaderViaList(IDataReader dataReader, IMappingEngineRunner mapper, Build buildFrom, ResolutionContext resolveUsingContext, Type elementType) in c:\dev\AutoMapper\src\AutoMapper\Mappers\DataReaderMapper.cs:line 78
            at AutoMapper.Mappers.DataReaderMapper.MapDataReaderToEnumerable(ResolutionContext context, IMappingEngineRunner mapper, Type destinationElementType, Boolean useYieldReturn) in c:\dev\AutoMapper\src\AutoMapper\Mappers\DataReaderMapper.cs:line 69
            at AutoMapper.Mappers.DataReaderMapper.Map(ResolutionContext context, IMappingEngineRunner mapper) in c:\dev\AutoMapper\src\AutoMapper\Mappers\DataReaderMapper.cs:line 29
            at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:line 246
       InnerException: 

Thanks for your help!

**Comment by jumas45** [comment]
I have resolved the issue. The problem was that some of the destination properties datatypes did not match the source destination properties. I had to create an explicit mapping for those fields and the problem went away.
